# Your OpenAI API key
OPENAI_API_KEY = "your-openai-key"

# Your Brevo API key (get it from Brevo dashboard)
BREVO_API_KEY = "your-brevo-key"

# Initial invite codes
[invite_codes]
BETA001 = false
BETA002 = false
BETA003 = false
BETA004 = false
BETA005 = false

# Admin users (can generate new invite codes)
[admin_users]
admin_emails = ["your-email@domain.com"] 