# Template for secrets.toml
# Copy this file to secrets.toml and fill in your actual API keys

# Your OpenAI API key
OPENAI_API_KEY = "your-openai-key-here"

# Your Brevo API key
BREVO_API_KEY = "your-brevo-key-here" 